name       : phonon
version    : 4.10.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/phonon/4.10.0/phonon-4.10.0.tar.xz : e2c10ecc7d2f3d3a0f80a63def789a875420b3d90062c26718dcfdaab8a5d03f
license    : LGPL-2.1
component  : desktop.multimedia
summary    : Qt-style interface for audio and video.
description: |
    Qt-style interface for audio and video.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - phonon-backend-gstreamer
setup      : |
    %cmake -DPHONON_BUILD_PHONON4QT5=TRUE .
build      : |
    %make
install    : |
    %make_install
