name       : phonon
version    : 4.9.1
release    : 7
source     :
    - https://cdn.download.kde.org/stable/phonon/4.9.1/phonon-4.9.1.tar.xz : 67bee986f85ca8b575186c8ba58a85886cb3b1c3567c86a118d56129f221e69c
license    : LGPL-2.1
component  : desktop.multimedia
summary    : Qt-style interface for audio and video.
description: |
    Qt-style interface for audio and video.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - phonon-backend-gstreamer
setup      : |
    %cmake -DPHONON_BUILD_PHONON4QT5=TRUE .
build      : |
    %make
install    : |
    %make_install
