name       : phonon
version    : 4.9.0
release    : 1
source     :
    - http://download.kde.org/stable/phonon/4.9.0/phonon-4.9.0.tar.xz : bb74b40f18ade1d9ab89ffcd7aeb7555be797ca395f1224c488b394da6deb0e0
license    : LGPL-2.1
component  : desktop.multimedia
summary    : Qt-style interface for audio and video.
description: |
    Qt-style interface for audio and video.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake -DPHONON_BUILD_PHONON4QT5=TRUE .
build      : |
    %make
install    : |
    %make_install
