name       : phonon
version    : 4.10.2
release    : 11
source     :
    - https://download.kde.org/stable/phonon/4.10.2/phonon-4.10.2.tar.xz : 34edb1985778575eb7004e4e45151cd7bc995f61ddd6ce3b050b97b7bd778809
license    : LGPL-2.1-only
component  : desktop.multimedia
summary    : Qt-style interface for audio and video.
description: |
    Qt-style interface for audio and video.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - phonon-backend-gstreamer
setup      : |
    %cmake_ninja -DPHONON_BUILD_PHONON4QT5=TRUE
build      : |
    %ninja_build
install    : |
    %ninja_install
