name       : phonon
version    : 4.10.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/phonon/4.10.1/phonon-4.10.1.tar.xz : e5a98df31aeffc22493afc8d6adbca5d6f0c27cc2eed73b3be05195321e08db7
license    : LGPL-2.1-only
component  : desktop.multimedia
summary    : Qt-style interface for audio and video.
description: |
    Qt-style interface for audio and video.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - phonon-backend-gstreamer
setup      : |
    %cmake_ninja -DPHONON_BUILD_PHONON4QT5=TRUE
build      : |
    %ninja_build
install    : |
    %ninja_install
